Close #16: Initialize main application
Boost Program Options usage
===========================

Logical way to start using Boost Program Options
is the tutorial
https://www.boost.org/doc/libs/1_68_0/doc/html/program_options/tutorial.html

It looks messy, but all becomes clear with full code example
https://www.boost.org/doc/libs/1_57_0/libs/program_options/example/first.cpp

I didn't find any default tools
to check whether input parameter is an existent file,
so I've made my own
(also checked whether it's a correct plain PGM image file).
In order to check whether all is good we simply use `operator!`,
which is a synonym to `fail()` member function
http://www.cplusplus.com/reference/ios/ios/fail/

Should install `libboost-program-options-dev` to run tests successfully
https://stackoverflow.com/a/20502807/1305036

Exceptions handling
===================

The code example has an ugly `try-catch` block within.
I know a modern approach called `Function-try-block`.
You should not create one more indentation level,
you just write a `try` word after the function signature
and use `catch` after the function block
https://en.cppreference.com/w/cpp/language/function-try-block

I didn't know whether I have to use `\n` or `std::endl`
in error output (`std::cerr` may be a regular file).
Example contains `\n`, but I don't like to use it in modern C++.
My concern was caused by the fact
that Python has a similar thing called `os.linesep`,
and documentation says that I shouldn't use it as line ending in files,
and I should use `\n` instead
https://docs.python.org/3/library/os.html#os.linesep
Though, it seems like C++ has no such limitation
and I can use `std::endl` freely for line endings in files
https://stackoverflow.com/a/213977/1305036

Project configuration
=====================

Add executable
--------------

First, I find `Boost` library using `find_package` command.
Then, I add an executable using `add_executable` command.
The first argument is the executable name (`stereo_parallel`)
and the second one is the source file (`main.cpp`)
https://cmake.org/cmake-tutorial/
After that, I use familiar steps:
specify `target_include_directories` and `target_link_libraries`.
Note that I should link Boost Program Options library
using `Boost_PROGRAM_OPTIONS_LIBRARY` variable
https://stackoverflow.com/q/3897839/1305036

Link dependencies with each other
---------------------------------

The project didn't compile.
I thought that the issue is a linking type
(shared versus static libraries)

Error without shared (with static)
`cmake .. -DBUILD_SHARED_LIBS=OFF && cmake --build .`

```
libpgm_io.a(pgm_io.cpp.o): In function `operator<<(std::ostream&, PGM_IO const&)':
pgm_io.cpp:(.text+0x477): undefined reference to `image_valid(Image const&)'
pgm_io.cpp:(.text+0x615): undefined reference to `get_pixel_index(Image const&, Pixel)'
libpgm_io.a(pgm_io.cpp.o): In function `operator>>(std::istream&, PGM_IO&)':
pgm_io.cpp:(.text+0xa9a): undefined reference to `get_pixel_index(Image const&, Pixel)'
collect2: error: ld returned 1 exit status
include/CMakeFiles/stereo_parallel.dir/build.make:97: recipe for target 'include/stereo_parallel' failed
make[2]: *** [include/stereo_parallel] Error 1
CMakeFiles/Makefile2:90: recipe for target 'include/CMakeFiles/stereo_parallel.dir/all' failed
make[1]: *** [include/CMakeFiles/stereo_parallel.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

With shared (instead of static)
`cmake .. -DBUILD_SHARED_LIBS=ON && cmake --build .`

```
libpgm_io.so: undefined reference to `image_valid(Image const&)'
libpgm_io.so: undefined reference to `get_pixel_index(Image const&, Pixel)'
collect2: error: ld returned 1 exit status
include/CMakeFiles/stereo_parallel.dir/build.make:97: recipe for target 'include/stereo_parallel' failed
make[2]: *** [include/stereo_parallel] Error 1
CMakeFiles/Makefile2:90: recipe for target 'include/CMakeFiles/stereo_parallel.dir/all' failed
make[1]: *** [include/CMakeFiles/stereo_parallel.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

It's appeared that I should link `image` library to `pgm_io` library,
because the second one didn't see the first one
```
target_link_libraries(
    pgm_io
    image
)
```

Usage
=====

Convert to plain PGM
`convert input -compress none output.pgm`
https://www.imagemagick.org/discourse-server/viewtopic.php?t=18720

Avoid usage of default constructor of `Image`
=============================================

The following error wasn't clear enough for me at first
https://travis-ci.org/char-lie/stereo-parallel/jobs/457129459

```
/home/travis/build/char-lie/stereo-parallel/include/image.hpp:46:8: error: constructor does not initialize these fields: width, height, max_value [cppcoreguidelines-pro-type-member-init,-warnings-as-errors]
struct Image
       ^
```

Documentation didn't clarify a lot.
I've got that it happened because I don't have a constructor,
but it didn't fail before
https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines-pro-type-member-init.html

If I don't use default constructor and assign a value immediately,
this works fine.
Let it be a solution at the moment.

Default exceptions are not nothrow copy constructible on Travis CI?
===================================================================

Got strange errors of Clang Tidy
https://travis-ci.org/char-lie/stereo-parallel/jobs/457608756

```
/home/travis/build/char-lie/stereo-parallel/include/main.cpp:80:15: error: thrown exception type is not nothrow copy constructible [cert-err60-cpp,-warnings-as-errors]
        throw std::invalid_argument("");
              ^
/home/travis/build/char-lie/stereo-parallel/include/main.cpp:87:15: error: thrown exception type is not nothrow copy constructible [cert-err60-cpp,-warnings-as-errors]
        throw std::invalid_argument("");
              ^
/home/travis/build/char-lie/stereo-parallel/include/main.cpp:91:15: error: thrown exception type is not nothrow copy constructible [cert-err60-cpp,-warnings-as-errors]
        throw std::logic_error("");
              ^
```

Cannot reproduce it on local machine, only Travis CI.
Documentation of the error
https://clang.llvm.org/extra/clang-tidy/checks/cert-err60-cpp.html
refers us to coding standard of Software Engineering Institute
of Carnegie Mellon University
https://wiki.sei.cmu.edu/confluence/display/cplusplus/ERR60-CPP.+Exception+objects+must+be+nothrow+copy+constructible
As long as during exception handling the exception is being copied,
the copy constructor shouldn't throw any exceptions.

`std::logic_error` is inherited from `std::exception`
https://en.cppreference.com/w/cpp/error/logic_error
`std::exception` seems to be marked as `noexcept`
https://en.cppreference.com/w/cpp/error/exception/exception
except the note

> Because copying std::exception is not permitted to throw exceptions,
> when derived classes (such as std::runtime_error)
> have to manage a user-defined diagnostic message,
> it is typically implemented as a copy-on-write string.

At the moment I don't understand what all this mean,
so I'll just treat the error as a warning.
Local downgrade of `clang`, `clang++` and `clang-tidy` to version `5.0`
didn't help to reproduce the issue locally.