Use `empty()` instead of `== ""`
Build failed with one more error
https://travis-ci.org/char-lie/stereo-parallel/jobs/452082015

```
/home/travis/build/char-lie/stereo-parallel/include/pgm_io.cpp:158:13:
error: the 'empty' method should be used to check for emptiness instead
of comparing to an empty object
[readability-container-size-empty,-warnings-as-errors]
        if (PGM_IO::read_pgm_instruction(in) != "")
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                !PGM_IO::read_pgm_instruction(in).empty()
```

That's reasonable: if there is a special check for a string emptiness,
it's better to use it.