Use sstream instead of strstream
When I used `strstream` there was a problem:
it had a garbage after end of the input,
so I had to use `std::ends` to end the string explicitly
https://openwatcom.users.c-cpp.narkive.com/7tzBBM6z/problem-woth-ostrstream#post4

It appeared that this library is deprecated
https://travis-ci.org/char-lie/stereo-parallel/jobs/450992702

```
In file included from /home/travis/build/char-lie/stereo-parallel/tests/pgm_io.cpp:27:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward/strstream:51:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward/backward_warning.h:32:2: error:
      This file includes at least one deprecated or antiquated header which may
      be removed without further notice at a future date. Please use a
      non-deprecated interface with equivalent functionality instead. For a
      listing of replacement headers and interfaces, consult the file
      backward_warning.h. To disable this warning use -Wno-deprecated.
      [-Werror,-W#warnings]
 ^
```

I should use `sstream` library instead.
It contains `ostringstream` class that doesn't need `std::ends` to end
the string.
https://stackoverflow.com/a/2820289/1305036