Remove old versions of compilers from CI
`g++4.9` and `clang++3.6` fail to compile the code
because it uses implicit copy constructor for `Image`
https://travis-ci.org/char-lie/stereo-parallel/builds/452085934

```
/home/travis/build/char-lie/stereo-parallel/tests/pgm_io.cpp:57:24: error: no
      viable conversion from 'Image' to 'ULONG' (aka 'unsigned long')
    struct Image image{*pgm_io.get_image()};
                       ^~~~~~~~~~~~~~~~~~~
/home/travis/build/char-lie/stereo-parallel/tests/pgm_io.cpp:57:43: error:
      missing field 'height' initializer [-Werror,-Wmissing-field-initializers]
    struct Image image{*pgm_io.get_image()};
                                          ^
```

The issue was discussed on bugtracker of GCC
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36750
as well as on CLang forum
http://clang-developers.42468.n3.nabble.com/Wmissing-field-initializers-td3761260.html

It was fixed in the nextt versions of compilers,
so I will simply remove them from CI.
Also, this will shorten time of tests running.