Mute google-runtime-int warning
I use `unsigned long` and it may cause problems
```
using ULONG = unsigned long;
              ^
/home/travis/build/char-lie/stereo-parallel/src/image.hpp:29:15: error: consider replacing 'unsigned long' with 'uint64' [google-runtime-int,-warnings-as-errors]
```

The warning is reasonable, because `long` may have 16 bits.
Though, I use it for size of image.
I'm not even sure that I will process images greater that 4k.

Don't remove this error -- just treat it as warning.