Close #100: Add ability to use CUDA for CSP solution
* Prepare `types.hpp` for CUDA

Add `__device__` and `__host__` macro stubs
to mark GPU and CPU code for CUDA
but still have an ability to compile it without CUDA.

* Prepare the code for the CUDA

Add default constructors for used structures,
because CUDA, unlike OpenCL,
needs it when I create a variable that will be populated later
by `populate_structures_gpu`.
Otherwise, the error like the following occurs
```
.../stereo-parallel/lib/solve_csp.cu(120): error: no default constructor exists for class "sp::graph::constraint::ConstraintGraph"

.../stereo-parallel/lib/solve_csp.cu(200): error: no default constructor exists for class "sp::graph::constraint::ConstraintGraph"
```
where I have `struct ConstraintGraph constraint_graph;`.

Add `__device__` keyword to functions
that should run on GPU.

Remove usage of nested namespaces from the code, running not only on CPU,
because CUDA 10 doesn't support C++17 features
https://devtalk.nvidia.com/default/topic/1043872/cuda-setup-and-installation/cuda-10-amp-vs2017-amp-c-17/post/5295730/#5295730
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#c-cplusplus-language-support

Use `BOOL` instead of `bool`.

Use `!defined((__CUDA_ARCH__)` in conjunction with
`!defined(__OPENCL_C_VERSION__)` instead of `#ifndef`.
This allows to use convenient things on CPU-only code
without getting compilation errors for GPU.
The final guard starts with
`#if !defined(__OPENCL_C_VERSION__) && !defined(__CUDA_ARCH__)`
and ends with
`#endif`

* Add CUDA source files

CMake allows usage of CUDA language
https://cmake.org/cmake/help/v3.11/command/enable_language.html
Though, it will search for .cu files to compile them with CUDA compiler.

In order to have .cu files with the same content as .cpp files,
I need to create the .cu files, include .cpp files there
and make this magic work only on CUDA compiler run with __CUDA_ARCH__
https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#cuda-arch

* Initialize CUDA calling code

Add error checkers got from
https://stackoverflow.com/a/14038590/1305036.

* Add CUDA program variables initialization

You should use `cudaMalloc` to allocate the GPU memory
(just like `malloc`),
and then use `cudaMemcpy` (like `memcpy`)
to load contents of local arrays into the GPU memory.
In the end, we should copy the result back
and use `cudaFree` to free the memory (just like `free`).

`cudaMemcpy` is different from `memcpy`
in the flag that should be provided:
`cudaMemcpyHostToDevice` if you want to copy from the host to GPU
and `cudaMemcpyDeviceToHost` in the reverse case.

Use the guide to know more
https://devblogs.nvidia.com/how-optimize-data-transfers-cuda-cc/

* Initiate CUDA device code

Start with function, populating the structures.

Use `#if defined(__CUDA_ARCH__)` in the function, or the error will
occur

```
.../lib/solve_csp.cu(47): error: no operator "=" matches these operands
            operand types are: sp::types::ULONG_ARRAY = unsigned int *

.../lib/solve_csp.cu(52): error: no operator "=" matches these operands
            operand types are: sp::types::ULONG_ARRAY = unsigned int *

.../lib/solve_csp.cu(59): error: no operator "=" matches these operands
            operand types are: sp::types::FLOAT_ARRAY = float *

.../lib/solve_csp.cu(63): error: no operator "=" matches these operands
            operand types are: sp::types::FLOAT_ARRAY = float *

.../lib/solve_csp.cu(64): error: no operator "=" matches these operands
            operand types are: sp::types::FLOAT_ARRAY = float *

.../lib/solve_csp.cu(67): error: no operator "=" matches these operands
            operand types are: sp::types::BOOL_ARRAY = int *

6 errors detected in the compilation of "/tmp/tmpxft_000047d4_00000000-4_solve_csp.cpp4.ii".
lib/CMakeFiles/cuda_csp.dir/build.make:75: recipe for target 'lib/CMakeFiles/cuda_csp.dir/solve_csp.cu.o' failed
make[2]: *** [lib/CMakeFiles/cuda_csp.dir/solve_csp.cu.o] Error 2
CMakeFiles/Makefile2:418: recipe for target 'lib/CMakeFiles/cuda_csp.dir/all' failed
make[1]: *** [lib/CMakeFiles/cuda_csp.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

* Implement CUDA CSP solution iteration

The function differs from the corresponding in OpenCL code:
it uses native synchronization ability (available from CUDA 9),
allowing to synchronize not only in current work group of threads,
but all threads (don't know whether it's limited to a kernel or not).
In my tests it appeared that this is faster than synchronization using
an additional global variable.

See example of use
https://stackoverflow.com/a/6405432/1305036
and detailed official documentation
https://devblogs.nvidia.com/cooperative-groups
to know more.

* Fix CUDA launch code

Remove reinitialization of synchronization helping variable.
Use only one value for the synchronization,
because cooperative groups makes local synchronization variable
redundant.
Use `cstdio` to make `printf` available.
We need to use `printf` for the error reports,
because device can use it, but cannot use `std::cout`.

* Shorten variable name

* Abort the execution on CUDA exception

* Remove errorneous memory copy from the non-existing variable

* Implement CUDA functions to call from the host

The two functions are for finding the best node
and to perform a single CSP iteration.

* Add function, calling CUDA code from the host

* Add headers for the functions powered by CUDA

* Add an ability to find labeling using CUDA

* Add an ability to specify CUDA through the CLI

* Fix the ability to use CUDA

* Add flags to allow compilation with CUDA and OpenCL

I forgot to add this for OpenCL before

* Require CMake 3.11+ and CUDA if the CUDA is needed

CMake 3.11 is the earliest version supporting CUDA language natively
through `enable_language` and `project` commands
https://cmake.org/cmake/help/v3.11/command/enable_language.html
https://cmake.org/cmake/help/v3.11/command/project.html

So, if the CUDA is needed,
we need to require newer version of CMake (not 3.9, but 3.11).
It's a bit problematic for Ubuntu 18.04,
because its default version is 3.10.2
https://launchpad.net/ubuntu/bionic/+source/cmake,
because you should download binaries of newer CMake
from the official assets
https://github.com/Kitware/CMake/releases/download/v3.11.4/cmake-3.11.4-Linux-x86_64.tar.gz
Though, with Ubuntu 20.04 we have CMake 3.16.3
https://launchpad.net/ubuntu/focal/+source/cmake
So, let's wait for the official support of Ubuntu 20.04 from Nvidia.

* Compile CUDA code, add include directories and inject define a macro variable

* Add the main CUDA compilation magic to CMake

* Close #106: Update copyright :christmas_tree:

This update is so late that I thought about skipping it to 2021.
Though, the big job regarding CUDA integration (feature #100)
is almost done and I can breathe easier.

* Add copyrights to CUDA-related headers

* Add copyright to the `.cu` files