Prepare the code for the CUDA
Add default constructors for used structures,
because CUDA, unlike OpenCL,
needs it when I create a variable that will be populated later
by `populate_structures_gpu`.
Otherwise, the error like the following occurs
```
.../stereo-parallel/lib/solve_csp.cu(120): error: no default constructor exists for class "sp::graph::constraint::ConstraintGraph"

.../stereo-parallel/lib/solve_csp.cu(200): error: no default constructor exists for class "sp::graph::constraint::ConstraintGraph"
```
where I have `struct ConstraintGraph constraint_graph;`.

Add `__device__` keyword to functions
that should run on GPU.

Remove usage of nested namespaces from the code, running not only on CPU,
because CUDA 10 doesn't support C++17 features
https://devtalk.nvidia.com/default/topic/1043872/cuda-setup-and-installation/cuda-10-amp-vs2017-amp-c-17/post/5295730/#5295730
https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#c-cplusplus-language-support

Use `BOOL` instead of `bool`.

Use `!defined((__CUDA_ARCH__)` in conjunction with
`!defined(__OPENCL_C_VERSION__)` instead of `#ifndef`.
This allows to use convenient things on CPU-only code
without getting compilation errors for GPU.
The final guard starts with
`#if !defined(__OPENCL_C_VERSION__) && !defined(__CUDA_ARCH__)`
and ends with
`#endif`