Don't use 'using' in global namespace
An error occurred during build
https://travis-ci.org/char-lie/stereo-parallel/jobs/449513554

```
/home/travis/build/char-lie/stereo-parallel/include/image.hpp:32:1: error: using declarations in the global namespace in headers are prohibited [google-global-names-in-headers,-warnings-as-errors]
using std::vector;
^
```

Reasonable enough: `#include` just includes source code of one file to another,
so global `using` will add some entities to another files implicitly,
and removal or changing of order of some included files
will lead to strange errors.