Remove redundant conversion to C-style string
When `ostrstream` was used,
it was needed to convert string to C-style string of type `char*`.
`ostringstream` can be constructed directly from `string`.
The old code produced the error
https://travis-ci.org/char-lie/stereo-parallel/jobs/451014544

```
/home/travis/build/char-lie/stereo-parallel/tests/pgm_io.cpp:147:36: error: redundant call to 'c_str' [readability-redundant-string-cstr,-warnings-as-errors]
    std::istringstream image_input{image_string.c_str()};
                                   ^~~~~~~~~~~~~~~~~~~~~
                                   image_string
```