Link `image` library to `pgm_io`
The project didn't compile.
I thought that the issue is a linking type
(shared versus static libraries)

Error without shared (with static)
`cmake .. -DBUILD_SHARED_LIBS=OFF && cmake --build .`

```
libpgm_io.a(pgm_io.cpp.o): In function `operator<<(std::ostream&, PGM_IO const&)':
pgm_io.cpp:(.text+0x477): undefined reference to `image_valid(Image const&)'
pgm_io.cpp:(.text+0x615): undefined reference to `get_pixel_index(Image const&, Pixel)'
libpgm_io.a(pgm_io.cpp.o): In function `operator>>(std::istream&, PGM_IO&)':
pgm_io.cpp:(.text+0xa9a): undefined reference to `get_pixel_index(Image const&, Pixel)'
collect2: error: ld returned 1 exit status
include/CMakeFiles/stereo_parallel.dir/build.make:97: recipe for target 'include/stereo_parallel' failed
make[2]: *** [include/stereo_parallel] Error 1
CMakeFiles/Makefile2:90: recipe for target 'include/CMakeFiles/stereo_parallel.dir/all' failed
make[1]: *** [include/CMakeFiles/stereo_parallel.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

With shared (instead of static)
`cmake .. -DBUILD_SHARED_LIBS=ON && cmake --build .`

```
libpgm_io.so: undefined reference to `image_valid(Image const&)'
libpgm_io.so: undefined reference to `get_pixel_index(Image const&, Pixel)'
collect2: error: ld returned 1 exit status
include/CMakeFiles/stereo_parallel.dir/build.make:97: recipe for target 'include/stereo_parallel' failed
make[2]: *** [include/stereo_parallel] Error 1
CMakeFiles/Makefile2:90: recipe for target 'include/CMakeFiles/stereo_parallel.dir/all' failed
make[1]: *** [include/CMakeFiles/stereo_parallel.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

It's appeared that I should link `image` library to `pgm_io` library,
because the second one didn't see the first one
```
target_link_libraries(
    pgm_io
    image
)
```