Close #43: Implement basic functionality for Image structure
Use 'std::vector' instead of 'std::shared_ptr'
==============================================

It's more convenient to store data array of `Image` as a `vector`
in order to access its elements and ease its construction.

Looks like Boost Test library has no specific tool
for comparison of arrays,
so I'll use a regular `BOOST_CHECK`.
Attempt to use `BOOST_CHECK_EQUAL` led to an error,
because in the case of failure the library cannot display wrong array

```
/usr/include/boost/test/tools/detail/print_helper.hpp:54:18: error: invalid operands to binary expression ('std::ostream' (aka 'basic_ostream<char>') and 'const std::vector<unsigned long, std::allocator<unsigned long> >')
            ostr << t;
            ~~~~ ^  ~
```

There is an alternative called `BOOST_TEST`,
but it wasn't found
https://travis-ci.org/char-lie/stereo-parallel/jobs/449521868

```
/home/travis/build/char-lie/stereo-parallel/tests/image.cpp:37:5: error: use of undeclared identifier 'BOOST_TEST' [clang-diagnostic-error]
    BOOST_TEST(image.data == vector<ULONG>({0, 1}));
    ^
```

Implement `Pixel` structure
===========================

In a function that will return pixel index by its position on an image
we will need to provide the position.
I'd like to provide a structure instead of two values,
because soon aggregate initialization will allow to use
`get_index(image, {.row = x, .column = y})`,
and this is more clear than `get_index(image, x, y)`.
https://en.cppreference.com/w/cpp/language/aggregate_initialization

Implement Image check and read functions
========================================

Header files usually contain prototypes of functions.
I implement prototypes for image validation, pixel index calculation and
its intensity fetch.
Next, I create corresponding source file with bodies of the functions.

Add Image source file to CMakeLists.txt
=======================================

We no longer need explicit specificaton of linker language,
because source file extension is enough.

Use MathJAX in Doxygen
======================

I use LaTeX code in documentation
by `\f[` to open code block and `\f]` to close it
https://www.stack.nl/~dimitri/doxygen/manual/formulas.html

I should enable `USE_MATHJAX` option in Doxyfile
to render formulas right
https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_use_mathjax

Don't use 'using' in global namespace
=====================================

An error occurred during build
https://travis-ci.org/char-lie/stereo-parallel/jobs/449513554

```
/home/travis/build/char-lie/stereo-parallel/include/image.hpp:32:1: error: using declarations in the global namespace in headers are prohibited [google-global-names-in-headers,-warnings-as-errors]
using std::vector;
^
```

Reasonable enough: `#include` just includes source code of one file to another,
so global `using` will add some entities to another files implicitly,
and removal or changing of order of some included files
will lead to strange errors.

Avoid implicit conversion to 'bool'
===================================

Another one fail in build
https://travis-ci.org/char-lie/stereo-parallel/jobs/449513554

```
/home/travis/build/char-lie/stereo-parallel/include/image.cpp:28:10: error: implicit cast 'ULONG' (aka 'unsigned long') -> bool [readability-implicit-bool-cast,-warnings-as-errors]
    if (!image.max_value || !image.width || !image.height)
        ~^~~~~
        (                == 0u)
/home/travis/build/char-lie/stereo-parallel/include/image.cpp:28:30: error: implicit cast 'ULONG' (aka 'unsigned long') -> bool [readability-implicit-bool-cast,-warnings-as-errors]
    if (!image.max_value || !image.width || !image.height)
                            ~^~~~~
                            (            == 0u)
/home/travis/build/char-lie/stereo-parallel/include/image.cpp:28:46: error: implicit cast 'ULONG' (aka 'unsigned long') -> bool [readability-implicit-bool-cast,-warnings-as-errors]
    if (!image.max_value || !image.width || !image.height)
                                            ~^~~~~       ~
                                            (             == 0u)
```

It's said that implicit conversion to `bool` may lead to bugs.
Okay, let's be explicit
https://clang.llvm.org/extra/clang-tidy/checks/readability-implicit-bool-conversion.html

Treat cppcoreguidelines-pro-type-vararg as warning
==================================================

An error occurred
https://travis-ci.org/char-lie/stereo-parallel/jobs/449517928

```
/home/travis/build/char-lie/stereo-parallel/tests/image.cpp:37:5: error: do not call c-style vararg functions [cppcoreguidelines-pro-type-vararg,-warnings-as-errors]
    BOOST_CHECK(image.data == vector<ULONG>({0, 1}));
    ^
/usr/include/boost/test/test_tools.hpp:110:45: note: expanded from macro 'BOOST_CHECK'
#define BOOST_CHECK( P )                    BOOST_CHECK_IMPL( (P), BOOST_TEST_STRINGIZE( P ), CHECK, CHECK_PRED )
                                            ^
/usr/include/boost/test/test_tools.hpp:91:5: note: expanded from macro 'BOOST_CHECK_IMPL'
    BOOST_TEST_TOOL_IMPL( check_impl, P, check_descr, TL, CT ), 0 );\
    ^
/usr/include/boost/test/test_tools.hpp:77:5: note: expanded from macro 'BOOST_TEST_TOOL_IMPL'
    ::boost::test_tools::tt_detail::func(                               \
    ^
```

I will not avoid usage of `BOOST_CHECK`,
so I'll treat the error as a warning.