Add clang-tidy configuration file
You can store configuration for clang-tidy in a separate file
http://clang.llvm.org/extra/clang-tidy

I enable all checks by `*`, and treated all warnings as errors first.

Then, I've got `clang-diagnostic-unused-command-line-argument` in arguments
passed by CMakeLists file

```
warning: /home/valera/prog/stereo-parallel/build/tests/: 'linker' input unused [clang-diagnostic-unused-command-line-argument]
warning: argument unused during compilation: '-D BOOST_TEST_DYN_LINK=1' [clang-diagnostic-unused-command-line-argument]
warning: argument unused during compilation: '-D BOOST_TEST_MODULE=Stereo Parallel tests' [clang-diagnostic-unused-command-line-argument]
warning: argument unused during compilation: '-c' [clang-diagnostic-unused-command-line-argument]
warning: argument unused during compilation: '-g' [clang-diagnostic-unused-command-line-argument]
```

I've removed definition of
`BOOST_TEST_DYN_LINK` and `BOOST_TEST_MODULE` macros
from CMakeLists.txt file of tests and compilation failed,
so I've downgraded the error to warning.

Also, I had `cert-err58-cpp` in the only test of the project

```
/home/valera/prog/stereo-parallel/tests/api.cpp:4:1: warning: initialization of 'compile_registrar40' with static storage duration may throw an exception that cannot be caught [cert-err58-cpp]
BOOST_AUTO_TEST_CASE(compile)
^
/usr/include/boost/test/unit_test_suite.hpp:209:9: note: expanded from macro 'BOOST_AUTO_TEST_CASE'
        BOOST_AUTO_TEST_CASE_NO_DECOR,                                  \
        ^
/usr/include/boost/test/tree/auto_registration.hpp:40:17: note: possibly throwing constructor declared here
                auto_test_unit_registrar( test_case* tc, decorator::collector& decorators, counter_t exp_fail = 0 );
                ^
/usr/bin/clang++ -DBOOST_TEST_DYN_LINK=1 -DBOOST_TEST_MODULE=Stereo Parallel tests -g -o CMakeFiles/test_executable.dir/api.cpp.o -c /home/valera/prog/stereo-parallel/tests/api.cpp
```

I googled the issue for several evenings,
and came to conclusion that it's better to add this error
to exceptions of `WarningsAsErrors` list.

Looks like that's all, but suddenly there appeared a strange error
`fuchsia-default-arguments,-warnings-as-errors`

```
/home/valera/prog/stereo-parallel/tests/api.cpp:4:1: error: calling a function that uses a default argument is disallowed [fuchsia-default-arguments,-warnings-as-errors]
BOOST_AUTO_TEST_CASE(compile)
^
/usr/include/boost/test/unit_test_suite.hpp:209:9: note: expanded from macro 'BOOST_AUTO_TEST_CASE'
        BOOST_AUTO_TEST_CASE_NO_DECOR,                                  \
        ^
/usr/include/boost/function/function_template.hpp:1056:13: note: default parameter was declared here
           ,typename boost::enable_if_c<
```

It's strange, because...is it bad to use default arguments
in C++ code in 2018?
Okay, let's read about it
https://clang.llvm.org/extra/clang-tidy/checks/fuchsia-default-arguments.html
This clarified almost nothing for me,
except I was assured that it really doesn't like default arguments.
What is `Fuchsia`?
It's an OS make by Google
https://fuchsia.googlesource.com
Nice.
The warning belons to this project.
This means that I can disable warnings of `fuchsia`.