Boost libraries can be added using double colons https://cmake.org/cmake/help/latest/module/FindBoost.html Use of double colon `::` in CMake is similar to their usage in C++: it's like a namespace for external libraries https://cmake.org/cmake/help/v3.0/policy/CMP0028.html The "namespace" should be created by the vendor. Boost does so, that's why we're happy to use this feature like `Boost::unit_test_framework`.
With MSVC 16 I've got a strange error
```
...\stereo-parallel\include\compile_cl.hpp(9,10): fatal error C1083: Cannot open include file: 'boost/compute.hpp': No such file or directory [...\stereo-parallel\build\lib\compile_cl.vcxproj]
```
But I've got this file and it works with g++!
I was wondering for a long time (several days) how to fix this.
It's appeared that I've used `BOOST_INCLUDE_DIRS` for `target_include_directories`
instead of `Boost_INCLUDE_DIRS` (the word `Boost` has only the first letter capitalized).

Also, this error has occurred when I tried to use multiple include directories.
The reason was a wrong paths separator (space instead of semicolon)
https://cmake.org/cmake/help/v3.11/prop_sf/INCLUDE_DIRECTORIES.html

Looks like I've almost never compiled the project without tests.
I've tried to do so under Windows in order to disable different parts of the project,
because I couldn't build it.
I've got such warning
```
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_TESTS
```
Just needed to add this option as well as `BUILD_DOC` and `WITH_CUDA`.

Perhabs the simplest error in this carnival of madness is
```
...\stereo-parallel\lib\constraint_graph.cpp(366,1): error C3016: 'i': index variable in OpenMP 'for' statement must have signed integral type [...\stereo-parallel\build\lib\constraint_graph.vc xproj]
```
Here is some information about the error
https://docs.microsoft.com/en-us/cpp/error-messages/compiler-errors-2/compiler-error-c3016?view=vs-2019
Here is more information regarding the limitation of OpenMP 2:
only signed types are allowed as loop indices
https://stackoverflow.com/a/2822064/1305036
Though, OpenMP 3 allows you to use unsigned types as well
https://stackoverflow.com/a/3988573/1305036
The thing is: g++ 4.4 and clang++ 3.9 already support this
(https://www.openmp.org/resources/openmp-compilers-tools),
while MSVC 16 (shipped with Visual Studio 2019 I currently use) seems not to
https://docs.microsoft.com/en-us/cpp/build/reference/openmp-enable-openmp-2-0-support?view=vs-2019

I fix the type and edit my CMakeLists.txt to allow using OpenMP 2 or higher.

Usage of `double` has lead to the following errors
```
.../stereo-parallel/lib/solve_csp.cu(83): error : a value of type "double *" cannot be assigned to an entity of type "FLOAT_ARRAY" [...\stereo-parallel\build\lib\cuda_csp.vcxproj]

.../stereo-parallel/lib/solve_csp.cu(87): error : a value of type "double *" cannot be assigned to an entity of type "FLOAT_ARRAY" [...\stereo-parallel\build\lib\cuda_csp.vcxproj]

.../stereo-parallel/lib/solve_csp.cu(88): error : a value of type "double *" cannot be assigned to an entity of type "FLOAT_ARRAY" [...\stereo-parallel\build\lib\cuda_csp.vcxproj]
```
I should use the `FLOAT` and other aliases to keep code consistent and avoid such errors.

Don't ignore the error.
`labeling_finder` contained `break` after the first label found.
It should keep going in order to find if there are more labels left,
because this is the case, meaning that the application behaves wrongly.

Inconsistency in data types has led to strange errors, which are hard to read
```
     Creating library .../stereo-parallel/build/lib/Release/stereo_parallel.lib and object .../stereo-parallel/build/lib/Release/stereo_parallel.exp
cuda_csp.lib(cuda_csp.obj) : error LNK2019: unresolved external symbol "void __cdecl choose_best_node_gpu(int *,unsigned int *,unsigned int *,float *,float *,float *,unsigned int,unsigned int,unsigned int,unsigned int,float,float,float,u nsigned int,unsigned int)" (?choose_best_node_gpu@@YAXPEAHPEAI1PEAM22IIIIMMMII@Z) referenced in function "void __cdecl gpu::csp_solution_cuda(struct sp::graph::constraint::ConstraintGraph *,struct gpu::CUDAProblem *)" (?csp_solution_cuda @gpu@@YAXPEAUConstraintGraph@constraint@graph@sp@@PEAUCUDAProblem@1@@Z) [...\stereo-parallel\build\lib\stereo_parallel.vcxproj]
    Hint on symbols that are defined and could potentially match:
      "void __cdecl choose_best_node_gpu(int *,unsigned int *,unsigned int *,double *,double *,double *,unsigned int,unsigned int,unsigned int,unsigned int,double,double,double,unsigned int,unsigned int)" (?choose_best_node_gpu@@YAXPEAHP
  EAI1PEAN22IIIINNNII@Z)
cuda_csp.lib(cuda_csp.obj) : error LNK2019: unresolved external symbol "void __cdecl csp_iteration_cuda(int *,int *,unsigned int *,unsigned int *,float *,float *,float *,unsigned int,unsigned int,unsigned int,unsigned int,float,float,flo at)" (?csp_iteration_cuda@@YAXPEAH0PEAI1PEAM22IIIIMMM@Z) referenced in function "void __cdecl gpu::csp_solution_cuda(struct sp::graph::constraint::ConstraintGraph *,struct gpu::CUDAProblem *)" (?csp_solution_cuda@gpu@@YAXPEAUConstraintGr aph@constraint@graph@sp@@PEAUCUDAProblem@1@@Z) [...\stereo-parallel\build\lib\stereo_parallel.vcxproj]
    Hint on symbols that are defined and could potentially match:
      "void __cdecl csp_iteration_cuda(int *,int *,unsigned int *,unsigned int *,double *,double *,double *,unsigned int,unsigned int,unsigned int,unsigned int,double,double,double)" (?csp_iteration_cuda@@YAXPEAH0PEAI1PEAN22IIIINNN@Z)
...\stereo-parallel\build\lib\Release\stereo_parallel.exe : fatal error LNK1120: 2 unresolved externals [...\stereo-parallel\build\lib\stereo_parallel.vcxproj]
```
Should use `float` for the `FLOAT` alias for each language (C++, OpenCL, CUDA).

The error
```
  gpu_csp.cpp
.../boost/compute/kernel.hpp(517,52): error C2039: 'type': is not a member of 'boost::enable_if<boost::compute::is_fundamental<T>,void>' [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
          with
          [
              T=sp::types::ULONG
          ]
.../boost/compute/kernel.hpp(517): message : see declaration of 'boost::enable_if<boost::compute::is_fundamental<T>,void>' [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
          with
          [
              T=sp::types::ULONG
          ]
.../boost/compute/kernel.hpp(371): message : see reference to class template instantiation 'boost::compute::detail::set_kernel_arg<T>' being compiled [...\stereo-parallel\build\lib \gpu_csp.vcxproj]
          with
          [
              T=sp::types::ULONG
          ]
...\stereo-parallel\lib\gpu_csp.cpp(165): message : see reference to function template instantiation 'void boost::compute::kernel::set_arg<sp::types::ULONG>(size_t,const T &)' being compiled [C:\Users\Valera\Documen ts\stereo-parallel\build\lib\gpu_csp.vcxproj]
          with
          [
              T=sp::types::ULONG
          ]
.../boost/compute/kernel.hpp(519,1): error C2955: 'boost::type': use of class template requires template argument list [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
.../boost/type.hpp(14): message : see declaration of 'boost::type' [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
```
was very hard to understand.
It refers to several static checks with templates and tells me only that there is something wrong with data types
and that this happens in line `165` of the `lib/gpu_csp.cpp` file.
I should either use `static_cast<cl_ulong>(x)` and `static_cast<cl_ulong>(y)`
or define these variables as `cl_ulong` in the loops,
because `unsigned` is not a proper data type for the OpenCL kernel.

This error was even harder to comprehand
```
  gpu_csp.cpp
.../boost/compute/type_traits/type_name.hpp(98,40): error C2027: use of undefined type 'boost::compute::detail::type_name_trait<T>' [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
          with
          [
              T=input_type
          ]
.../boost/compute/type_traits/type_name.hpp(98): message : see declaration of 'boost::compute::detail::type_name_trait<T>' [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
          with
          [
              T=input_type
          ]
.../boost/compute/algorithm/copy.hpp(230): message : see reference to function template instantiation 'const char *boost::compute::type_name<input_type>(void)' being compiled [...\ stereo-parallel\build\lib\gpu_csp.vcxproj]
.../boost/compute/algorithm/copy.hpp(860): message : see reference to function template instantiation 'OutputIterator boost::compute::detail::dispatch_copy<InputIterator,OutputIterator>(InputIterator,In putIterator,OutputIterator,boost::compute::command_queue &,const boost::compute::wait_list &,void *)' being compiled [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
          with
          [
              OutputIterator=boost::compute::buffer_iterator<cl_ulong>,
              InputIterator=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<sp::types::ULONG>>>
          ]
.../boost/compute/container/vector.hpp(562): message : see reference to function template instantiation 'OutputIterator boost::compute::copy<InputIterator,boost::compute::buffer_iterator<T>>(InputIterat or,InputIterator,OutputIterator,boost::compute::command_queue &,const boost::compute::wait_list &)' being compiled [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
          with
          [
              OutputIterator=boost::compute::buffer_iterator<cl_ulong>,
              InputIterator=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<sp::types::ULONG>>>,
              T=cl_ulong
          ]
...\stereo-parallel\lib\gpu_csp.cpp(48): message : see reference to function template instantiation 'void boost::compute::vector<cl_ulong,boost::compute::buffer_allocator<T>>::assign<std::_Vector_const_iterator<std: :_Vector_val<std::_Simple_types<_Ty>>>>(InputIterator,InputIterator,boost::compute::command_queue &)' being compiled [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
          with
          [
              T=cl_ulong,
              _Ty=sp::types::ULONG,
              InputIterator=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<sp::types::ULONG>>>
          ]
...\stereo-parallel\lib\gpu_csp.cpp(44): message : see reference to function template instantiation 'void boost::compute::vector<cl_ulong,boost::compute::buffer_allocator<T>>::assign<std::_Vector_const_iterator<std: :_Vector_val<std::_Simple_types<_Ty>>>>(InputIterator,InputIterator,boost::compute::command_queue &)' being compiled [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
          with
          [
              T=cl_ulong,
              _Ty=sp::types::ULONG,
              InputIterator=std::_Vector_const_iterator<std::_Vector_val<std::_Simple_types<sp::types::ULONG>>>
          ]
.../boost/compute/type_traits/type_name.hpp(98,1): error C3861: 'value': identifier not found [...\stereo-parallel\build\lib\gpu_csp.vcxproj]
```
It's very long and loooks like the previous problem,
so I thought that I've not fixed it yet.

For some reason,
`boost::compute::vector::assign` with g++/clang++
can copy a vector of one type to the vector of another type,
while it cannot with MSVC.
So, I've needed to use `std::copy`
https://stackoverflow.com/a/14977805/1305036
In order to speed up the process slightly,
I use `boost::compute::vector::reserve`,
which is an analogue for `std::vector::reserve`
and allocates the space for the specified number of entities,
but without creating them (the size of the vector doesn't change)
https://en.cppreference.com/w/cpp/container/vector/reserve
Do **not** confuse it with `std::vector::resize`!
The `resize` function changes the `size` as well,
so newly inserted elements will be pushed after the `size` initialized elements
https://en.cppreference.com/w/cpp/container/vector/resize

To be completely sure that I'm doing the right thing,
I call `std::vector::clear` on the target vector before copying the data
https://en.cppreference.com/w/cpp/container/vector/clear

The following linking errors
```
  Building Custom Rule .../stereo-parallel/lib/CMakeLists.txt
     Creating library .../stereo-parallel/build/lib/Release/stereo_parallel.lib and object .../stereo-parallel/build/lib/Release/stereo_parallel.exp
cuda_csp.lib(cuda_csp.obj) : error LNK2019: unresolved external symbol __cudaRegisterLinkedBinary_43_tmpxft_000039a8_00000000_7_cuda_csp_cpp1_ii_c60de6d0 referenced in function "void __cdecl __sti____cudaRegisterAll(void)" (?__sti____cud aRegisterAll@@YAXXZ) [...\stereo-parallel\build\lib\stereo_parallel.vcxproj]
cuda_csp.lib(solve_csp.obj) : error LNK2019: unresolved external symbol __cudaRegisterLinkedBinary_44_tmpxft_00002ae0_00000000_7_solve_csp_cpp1_ii_3441deaa referenced in function "void __cdecl __sti____cudaRegisterAll(void)" (?__sti____c udaRegisterAll@@YAXXZ) [...\stereo-parallel\build\lib\stereo_parallel.vcxproj]
...\stereo-parallel\build\lib\Release\stereo_parallel.exe : fatal error LNK1120: 2 unresolved externals [...\stereo-parallel\build\lib\stereo_parallel.vcxproj]
```
have almost made me mad.
After two weeks of dispair, messing with compilation flags, different versions of libraries, googling and so on,
I've finally found the solution
https://stackoverflow.com/a/51353324/1305036
To enable `CUDA_RESOLVE_DEVICE_SYMBOLS` flag.
It looks like `CUDA_SEPARABLE_COMPILATION`,
but it's not the same!
This flags are both needed for the separable compilation
(as consequence, for cooperative groups).

The final properties to gather the project are
```
set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -arch=sm_60")
set_target_properties(cuda_csp PROPERTIES
    CUDA_SEPARABLE_COMPILATION ON
    CUDA_RESOLVE_DEVICE_SYMBOLS ON
)
```

Remove redundant `changed` member variable from the `include/gpu_csp.hpp`
Remove redundant `data` vector.

The warnings
```
  main.cpp
...\stereo-parallel\lib\main.cpp(153,39): warning C4244: '=': conversion from 'unsigned long' to 'sp::types::FLOAT', possible loss of data [...\stereo-parallel\build\lib\stereo_parallel.vcxproj ]
...\stereo-parallel\lib\main.cpp(160,40): warning C4244: '=': conversion from 'unsigned long' to 'sp::types::FLOAT', possible loss of data [...\stereo-parallel\build\lib\stereo_parallel.vcxproj ]
```
pay my attention to the fact of a bit wrong parsing of smoothness and cleanness parameters.

Use `static_cast<FLOAT>(0)` instead of `0` to fill the `std::vector<FLOAT>` to avoid the error
```
  lowest_penalties.cpp
...\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\include\xutility(3814,24): warning C4244: '=': conversion from 'const _Ty' to 'float', possible loss of data [...\stereo-parall el\build\lib\lowest_penalties.vcxproj]
          with
          [
              _Ty=int
          ]
...\stereo-parallel\lib\lowest_penalties.cpp(52): message : see reference to function template instantiation 'void std::fill<std::_Vector_iterator<std::_Vector_val<std::_Simple_types<_Ty>>>,int>(const _FwdIt,const _ FwdIt,const int &)' being compiled [...\stereo-parallel\build\lib\lowest_penalties.vcxproj]
          with
          [
              _Ty=sp::types::FLOAT,
              _FwdIt=std::_Vector_iterator<std::_Vector_val<std::_Simple_types<sp::types::FLOAT>>>
          ]
```

I would risk and ignore this warning at the moment
```
  labeling_finder.cpp
...\stereo-parallel\lib\labeling_finder.cpp(234,47): warning C4267: 'initializing': conversion from 'size_t' to 'sp::types::ULONG', possible loss of data [...\stereo-parallel\build\lib\labeling _finder.vcxproj]
```