Close #14: Implement Image structure
Add Image structure
===================

At the moment we don't need anything to do with the structure,
so the module doesn't have any functions.

Types' definitions are useful to run code on CPU and GPU:
I will control them by macros.

In C++ we have a `shared_ptr` that deallocates memory automatically
using RAII.
That's why I use it instead of pure pointer.
Though, on GPU I'll use regular pointer.

Add Image library to CMake project
==================================

To make the Image structure available in unit tests
we can create a library for it.

Use `add_library`.
the first argument is a name of the library.
It should be unique for all project in order to have an ability
to add the library to any other library or executable.
The next arguments are files that need to be included into the library.
There is also a possibility to choose between static, shared library or
module mode.
By default, static library is used.
This provokes creation of archived object file that will be linked by
linker during project build.
This allows you to catch unresolved symbols on build stage.
If `BUILD_SHARED_LIBS` flag is enabled, the library will be built as a
shared and will be loaded at runtime.
This allows you to send updates of your project by smaller parts
without need to recompile it.
Also, there is a `MODULE` option, and I didn't get its meaning.
I leave this behavior, because I don't see a reason to write more words.
Let user decide how to compile libraries of the project
https://cmake.org/cmake/help/v3.0/command/add_library.html

The project didn't compile,
because CMake didn't know what language it should use
to link the `image.hpp` file.

```
-- The CXX compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   unit_test_framework
-- Configuring done
CMake Error: Cannot determine link language for target "image".
CMake Error: CMake can not determine linker language for target:
image
-- Generating done
-- Build files have been written to:
```

Specifying project language didn't help
https://stackoverflow.com/a/11802004/1305036

From CMake mailing list I've learnt `set_target_properties` command
https://cmake.org/pipermail/cmake/2006-July/010380.html
I should set `linker_language` property for `image` library to
`CXX`.
So easy.
As I understand,
the point is that `image.hpp` file is not a source file,
and CMake is not quite sure that it's a C++ file.
I don't know for sure.

Next, I should specify include directories of the target.
It was already described in commit
3b2fee105da8950fa38216b3257737a06825dd37
I'll add one note:
if I remove the last parameter `${CMAKE_CURRENT_SOURCE_DIR}`
of the command `target_include_directories`,
the project will fail on attempt to include `image.hpp` to a module.

Implement a simple test for Image
=================================

I just check that I can construct the Image instance
and that all fields are named and set correctly.
Now I can add `image` test to the project
and link `image` library to tests.

Move BOOST_TEST_MODULE macro to API test file
=============================================

It was hard to find out why linking of tests' executable fails with

```
CMakeFiles/test_executable.dir/image.cpp.o: In function `init_unit_test()':
image.cpp:(.text+0xa6): multiple definition of `init_unit_test()'
CMakeFiles/test_executable.dir/api.cpp.o:api.cpp:(.text+0x0): first defined here
CMakeFiles/test_executable.dir/image.cpp.o: In function `main':
image.cpp:(.text+0x148): multiple definition of `main'
CMakeFiles/test_executable.dir/api.cpp.o:api.cpp:(.text+0xa2): first defined here
collect2: error: ld returned 1 exit status
tests/CMakeFiles/test_executable.dir/build.make:122: recipe for target 'tests/test_executable' failed
make[2]: *** [tests/test_executable] Error 1
CMakeFiles/Makefile2:140: recipe for target 'tests/CMakeFiles/test_executable.dir/all' failed
make[1]: *** [tests/CMakeFiles/test_executable.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

Finally, I've found the answer
https://groups.google.com/forum/#!topic/boost-list/BoZ1eBLN5Mw

I should use `BOOST_TEST_MODULE` only in one test file.
I just move definition of this macro from CMakeLists to API test file
and it works!

Add test suite to API test file
===============================

Now I have several files with tests
and it's convenient to start grouping tests by test suites.
You can mark the beginning of a test suite by
`BOOST_AUTO_TEST_SUITE(test_suite_name)`
and end it by `BOOST_AUTO_TEST_SUITE_END()`
https://www.boost.org/doc/libs/1_60_0/libs/test/doc/html/boost_test/tests_organization/test_suite.html

Fix llvm-header-guard error
===========================

Build failed
https://travis-ci.org/char-lie/stereo-parallel/jobs/443290526

```
/home/travis/build/char-lie/stereo-parallel/src/image.hpp:24:9: error:
header guard does not follow preferred style
[llvm-header-guard,-warnings-as-errors]
        ^~~~~~~
        _HOME_TRAVIS_BUILD_CHAR_LIE_STEREO_PARALLEL_SRC_IMAGE_HPP
```

Description of failed rule didn't get much information
about proper format.
https://clang.llvm.org/extra/clang-tidy/checks/llvm-header-guard.html

Linter proposed me to place full path
to `image.hpp` file into guard name.
On StackOverflow
https://stackoverflow.com/a/43881045/1305036
I've found a link to tests of clang-tidy
https://github.com/llvm-mirror/clang-tools-extra/blob/c30b89a5fed67aff8eead6412b97af97afdee019/unittests/clang-tidy/LLVMModuleTest.cpp
There I see that files in tests are placed in `include` folder.

I need to rename `src` folder to `include`
and change corresponding reference in main CMakeLists.txt file.
Perfect, this works!

Fix llvm-include-order
======================

Another error is a wrong order of includes in test file
https://travis-ci.org/char-lie/stereo-parallel/jobs/443290526

```
/home/travis/build/char-lie/stereo-parallel/tests/image.cpp:24:1: error: #includes are not sorted properly [llvm-include-order,-warnings-as-errors]
^        ~~~~~~~~~~~~~~~~~~~~~~~~~~
         "image.hpp"
```

Documentation to this error refers us to coding standards
https://clang.llvm.org/extra/clang-tidy/checks/llvm-include-order.html
It says that main module header should come first
http://llvm.org/docs/CodingStandards.html#include-style
This clarifies a lot: the test file is called `image.cpp`
and it includes `image.hpp` module in double quotes.
So, the linter recognizes the file as a header of the test.
Use angle brackets to destroy this error.

Trait google-runtime-int as a warning
=====================================

I use `unsigned long` and it may cause problems

```
using ULONG = unsigned long;
              ^
/home/travis/build/char-lie/stereo-parallel/src/image.hpp:29:15: error: consider replacing 'unsigned long' with 'uint64' [google-runtime-int,-warnings-as-errors]
```

The warning is reasonable, because `long` may have 16 bits.
Though, I use it for size of image.
I'm not even sure that I will process images greater that 4k.

Don't remove this error -- just treat it as a warning.

Fix clang-diagnostic-c++11-extensions
=====================================

I've got errors

```
/home/travis/build/char-lie/stereo-parallel/src/image.hpp:29:15: error: alias declarations are a C++11 extension [clang-diagnostic-c++11-extensions,-warnings-as-errors]
using ULONG = unsigned long;
              ^
/home/travis/build/char-lie/stereo-parallel/src/image.hpp:29:15: error: consider replacing 'unsigned long' with 'uint64' [google-runtime-int,-warnings-as-errors]
/home/travis/build/char-lie/stereo-parallel/src/image.hpp:30:15: error: alias declarations are a C++11 extension [clang-diagnostic-c++11-extensions,-warnings-as-errors]
using FLOAT = double;
              ^
/home/travis/build/char-lie/stereo-parallel/src/image.hpp:31:19: error: alias declarations are a C++11 extension [clang-diagnostic-c++11-extensions,-warnings-as-errors]
using FLOAT_PTR = std::shared_ptr<FLOAT>;
                  ^
/home/travis/build/char-lie/stereo-parallel/src/image.hpp:31:19: error: no template named 'shared_ptr' in namespace 'std'; did you mean 'boost::shared_ptr'? [clang-diagnostic-error]
using FLOAT_PTR = std::shared_ptr<FLOAT>;
                  ^~~~~~~~~~~~~~~~
                  boost::shared_ptr
/usr/include/boost/smart_ptr/shared_ptr.hpp:722:36: note: 'boost::shared_ptr' declared here
    template<class Y> friend class shared_ptr;
                                   ^
```

C++11 should be set explicitly im CMake project file
using `CMAKE_CXX_STANDARD` and `CMAKE_CXX_STANDARD_REQUIRED`
https://crascit.com/2015/03/28/enabling-cxx11-in-cmake/

`CMAKE_CXX_STANDARD` property specifies `CXX_STANDARD` property
for each target
https://cmake.org/cmake/help/v3.1/variable/CMAKE_CXX_STANDARD.html
`CXX_STANDARD` property specifies standard that should be used.
Available values are `98`, `11` and `14`
https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD.html

Property `CMAKE_CXX_STANDARD_REQUIRED` sets `CXX_STANDARD_REQUIRED`
for each target
https://cmake.org/cmake/help/v3.1/variable/CMAKE_CXX_STANDARD_REQUIRED.html
`CXX_STANDARD_REQUIRED` is a boolean flag.
If it's `ON`, this means that specified standard is required
and build will fail if needed version of the language
is not supported by compiler
https://cmake.org/cmake/help/v3.1/prop_tgt/CXX_STANDARD_REQUIRED.html

I've found these descriptions in documentation for CMake 3.1,
so, as I understand, it won't work with CMake 3.0 and earlier.
On StackOverflow it's said that there is a bug on MacOS
https://stackoverflow.com/a/31010221/1305036

Will fix these things later,
because this branch lives for too long already.

Remove comparison with null pointer
===================================

Travis CI job failed again
https://travis-ci.org/char-lie/stereo-parallel/jobs/443349369

There is ability to display null pointer

```
/usr/include/boost/test/test_tools.hpp:326:14: error: use of overloaded operator
      '<<' is ambiguous (with operand types 'std::ostream' (aka
      'basic_ostream<char>') and 'const nullptr_t')
        ostr << t; // by default print the value
        ~~~~ ^  ~
```

Maybe there is a special check against null pointer?
https://stackoverflow.com/a/37673842/1305036

`BOOST_CHECK` contains vararg function and clang-tidy doesn't like it

```
/home/travis/build/char-lie/stereo-parallel/tests/image.cpp:34:5: error: do not call c-style vararg functions [cppcoreguidelines-pro-type-vararg,-warnings-as-errors]
    BOOST_CHECK(!image.data);
    ^
```

At the moment I'll avoid usage of this function
and will not check that the pointer is actually null.

Add source directory to Doxyfile
================================

First, we should change `COPYONLY` parameter in `configure_file` command
in CMakeLists.txt of documentation to `@ONLY`.
If you remember, in c6f7fd797a0b57678fa4db124a0277c0f4d9463d
`COPYONLY` parameter was used to copy Doxygen configuration file
to the `build` directory.
Now we need to have an ability to set a directory with source files,
that contain documentation.
`@ONLY` parameter allows to use `@STEREO_PARALLEL_SOURCE_DIR@`,
and it will be replaced by `$STEREO_PARALLEL_SOURCE_DIR`
https://cmake.org/cmake/help/v3.0/command/configure_file.html

Needed parameter in Doxyfile called `INPUT`
https://www.stack.nl/~dimitri/doxygen/manual/config.html#cfg_input

Set CMP0057 policy to new when needed
=====================================

I've got an error when tried to buid the project with documentation

```
CMake Warning (dev) in /usr/share/cmake-3.10/Modules/FindDoxygen.cmake:
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  docs/CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/share/cmake-3.10/Modules/FindDoxygen.cmake:542 (elseif):
  given arguments:

    "NOT" "doxygen" "IN_LIST" "Doxygen_FIND_COMPONENTS"

  Unknown arguments specified
Call Stack (most recent call first):
  docs/CMakeLists.txt:4 (find_package)
```

Something strange.
You can see tha code that looks like a string
from the error in CMake source code
https://gitlab.kitware.com/cmake/cmake/blob/1e6b14f979a7f43e3529b51d5a8557feefd8f0bf/Modules/FindDoxygen.cmake#L478

There we can see a solution
https://gitlab.kitware.com/cmake/cmake/issues/18361

Just to set

```
if(POLICY CMP0057)
  cmake_policy(SET CMP0057 NEW)
endif()
```

This works fine.

Add documentation to type aliases in image module
=================================================

When I've added a documentation for type aliases,
it didn't appear in built documentation.
The solution is simple:
I should document the file.
This means that I can simply add a comment with `@file` in it.
https://stackoverflow.com/a/12041646/1305036

Now on page of the file in documentation I have a hyperlink
`Go to the documentation of this file`.