Use explicit comparison and character read
Travis-CI says that I use a garbage value
https://travis-ci.org/char-lie/stereo-parallel/jobs/458161935

```
/home/travis/build/char-lie/stereo-parallel/include/pgm_io.cpp:75:27: error: The left operand of '==' is a garbage value [clang-analyzer-core.UndefinedBinaryOperatorResult,-warnings-as-errors]
        if (current_input == '#')
```

Looks like I shouldn't use `in.get`
and should use `in >> current_input` instead.

Errors with implicit cast are clear.
Stream cast instead of `good` usage
```
/home/travis/build/char-lie/stereo-parallel/include/pgm_io.cpp:73:30: error: implicit cast 'void *' -> bool [readability-implicit-bool-cast,-warnings-as-errors]
    for (char current_input; in && !in.eof(); in.get(current_input))
                             ^~
                             ( != nullptr)
```
and `isspace` cast (I thought, it's `bool`, but it returns an `int`)

```
/home/travis/build/char-lie/stereo-parallel/include/pgm_io.cpp:79:44: error: implicit cast 'int' -> bool [readability-implicit-bool-cast,-warnings-as-errors]
        else if (current_input != '\0' && !std::isspace(current_input))
                                          ~^~~                        ~
                                          (                            == 0)
```