Close #15: Implement PGM format reader and writer
Preface
========

I'm really tired (physically), so this commit (and some another commits) will not contain a lot of _blog-like_ entries,
but it still has useful information.
Also, you can read documentation to `PGM_IO` class to know more.
I want to implement parallel algorithm for stereo vision faster,
but I want the repository to look very good as well.
I even forgot to populate contributing guide with used code style.
I've just created the issue https://github.com/char-lie/stereo-parallel/issues/46.

Use `3x2` image in tests instead of `2x2`
=========================================

It's a good idea to use image with different width and height,
because pixels fetch depends on these numbers
and it would be hard to find errors connected with replaced width and
height in the functions if test images were square.

Implement PGM format reader
===========================

Plain PGM image format was chosen,
because it's simple and represents grayscale images
with configurable maximal intensity.
This allows to store disparity map
with values that overflow `255`
http://netpbm.sourceforge.net/doc/pgm.html

Overloaded `<<` and `>>` operators allow us to read and write images
easily in usual way.
Only `operator>>` needs to be a `friend` of the `PGM_IO` class,
because it uses `read_ppm_instruction` class member
that was decided to be private.
Though, further `operator<<` was made a friend of the `PGM_IO` too.
This allows to have a normal documentation for the operator
without adding `@file` comment.
Also this looks more normal and consistent with `operator>>`.

Use `constexpr` keyword for constant string
===========================================

It's not a good idea to use `std::string` for a static constant string,
because you can't know for sure when it will be destroyed.
If I use a constant `char` pointer, I should use `constexpr`
in order to have an ability to make this member `static`
https://stackoverflow.com/a/9657064/1305036

Otherwise, an error occurs

```
.../stereo-parallel/include/pgm_io.hpp:42:24: error: non-const static data member must be initialized out of line [clang-diagnostic-error]
    static const char* FORMAT_CODE = "P2";
                       ^
```

Pass by value and use `std::move` instead of const reference to pointer
=======================================================================

It's a habit -- to use a constant reference to a variable
that doesn't need to be copied.
Clang Tidy proposed me to pass a value of a pointer instead,
but use `std::move` to move its value
and let a compiler to decide how to optimize this assignment
https://clang.llvm.org/extra/clang-tidy/checks/modernize-pass-by-value.html

Here is how it told me to do so

```
.../stereo-parallel/include/pgm_io.hpp:47:21: error: pass by value and use std::move [modernize-pass-by-value,-warnings-as-errors]
    explicit PGM_IO(std::shared_ptr<struct Image> image): image{image}
                    ^                                           ~~~~~~
                                                                std::move()
.../stereo-parallel/include/pgm_io.hpp:47:65: error: parameter 'image' is passed by value and only copied once; consider moving it to avoid unnecessary copies [performance-unnecessary-value-param,-warnings-as-errors]
    explicit PGM_IO(std::shared_ptr<struct Image> image): image{image}
                                                                ^~~~~~
                                                                std::move()
```

Implement special member functions for PGM_IO
=============================================

Clang Tidy wanted me to implement several special member functions.
Okay, let it be to avoid this error

```
.../stereo-parallel/include/pgm_io.hpp:32:7: error: class 'PGM_IO' defines a default destructor, a copy constructor and a move constructor but does not define a copy assignment operator or a move assignment operator [hicpp-special-member-functions,-warnings-as-errors]
class PGM_IO
      ^
```

Use `std::make_shared` instead of `std::shared_ptr` cast from pure pointer
==========================================================================

I really didn't know how to avoid an old `new` operator
when creating a shared pointer to a new object.
Clang Tidy has shown me the right way to do this:
just call `std::make_shared` and pass the object there
https://clang.llvm.org/extra/clang-tidy/checks/modernize-make-shared.html

When I use `new` and `std::shared_ptr` constructor, the error occurres

```
.../stereo-parallel/include/pgm_io.cpp:112:9: error: use std::make_shared instead [modernize-make-shared,-warnings-as-errors]
        std::shared_ptr<struct Image>(new Image{0, 0, 0, {}});
        ^~~~~~~~~~~~~~~~              ~~~~~~~~~
        std::make_shared
```

Use magic number instead of non-constexpr functions for static constant
=======================================================================

`ceil` and `log10` functions have no `constexpr` overloads,
so I just use a magic number to avoid the error

```
.../stereo-parallel/include/pgm_io.hpp:89:37: error: constexpr variable 'MAX_COLOR_DIGITS' must be initialized by a constant expression
    static constexpr const unsigned MAX_COLOR_DIGITS = ceil(log10(MAX_VALUE_LIMIT));      
                                    ^                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.../stereo-parallel/include/pgm_io.hpp:89:56: note: non-constexpr function 'ceil' cannot be used in a constant expression
    static constexpr const unsigned MAX_COLOR_DIGITS = ceil(log10(MAX_VALUE_LIMIT));
```


Use `std::sstream` instead of `std::strstream`
==============================================

When I used `std::strstream` there was a problem:
it had a garbage after end of the input,
so I had to use `std::ends` to end the string explicitly
https://openwatcom.users.c-cpp.narkive.com/7tzBBM6z/problem-woth-ostrstream#post4

It appeared that this library is deprecated
https://travis-ci.org/char-lie/stereo-parallel/jobs/450992702

and I've got an error

```
In file included from /home/travis/build/char-lie/stereo-parallel/tests/pgm_io.cpp:27:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward/strstream:51:
/usr/bin/../lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/backward/backward_warning.h:32:2: error:
      This file includes at least one deprecated or antiquated header which may
      be removed without further notice at a future date. Please use a
      non-deprecated interface with equivalent functionality instead. For a
      listing of replacement headers and interfaces, consult the file
      backward_warning.h. To disable this warning use -Wno-deprecated.
      [-Werror,-W#warnings]
 ^
```

I should use `sstream` library instead.
It contains `ostringstream` class that doesn't need `std::ends` to end
the string.
https://stackoverflow.com/a/2820289/1305036

Remove redundant conversion to C-style string
=============================================

When `ostrstream` was used,
it was needed to convert string to C-style string of type `char*`.
`ostringstream` can be constructed directly from `string`.
The old code produced the error
https://travis-ci.org/char-lie/stereo-parallel/jobs/451014544

```
/home/travis/build/char-lie/stereo-parallel/tests/pgm_io.cpp:147:36: error: redundant call to 'c_str' [readability-redundant-string-cstr,-warnings-as-errors]
    std::istringstream image_input{image_string.c_str()};
                                   ^~~~~~~~~~~~~~~~~~~~~
                                   image_string
```

Mark pointer check as required
==============================

If we have a null pointer instead of an image pointer,
tests that check properties of the image will fail
while trying to dereference null pointer.
It's better to end the test if image pointer check fails.

Set `failbit` when `std::invalid_argument` thrown
=================================================

I guess, it's better to set a fail bit rather than throw an exception
on wrong input file format.

Catch error by reference
========================

Errors occurred
https://travis-ci.org/char-lie/stereo-parallel/jobs/452082015

```
/home/travis/build/char-lie/stereo-parallel/include/pgm_io.cpp:126:12: error: catch handler catches by value; should catch by reference instead [cert-err09-cpp,-warnings-as-errors]
    catch (std::invalid_argument)
           ^
/home/travis/build/char-lie/stereo-parallel/include/pgm_io.cpp:148:20: error: catch handler catches by value; should catch by reference instead [cert-err09-cpp,-warnings-as-errors]
            catch (std::invalid_argument)
                   ^
```

It's recommended to catch an error by reference, not by value,
in this case
https://clang.llvm.org/extra/clang-tidy/checks/misc-throw-by-value-catch-by-reference.html

Use `empty()` instead of `== ""`
================================

Build failed with one more error
https://travis-ci.org/char-lie/stereo-parallel/jobs/452082015

```
/home/travis/build/char-lie/stereo-parallel/include/pgm_io.cpp:158:13:
error: the 'empty' method should be used to check for emptiness instead
of comparing to an empty object
[readability-container-size-empty,-warnings-as-errors]
        if (PGM_IO::read_pgm_instruction(in) != "")
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                !PGM_IO::read_pgm_instruction(in).empty()
```

That's reasonable: if there is a special check for a string emptiness,
it's better to use it.

Remove old versions of compilers from CI
========================================

`g++4.9` and `clang++3.6` fail to compile the code
because it uses implicit copy constructor for `Image`
https://travis-ci.org/char-lie/stereo-parallel/builds/452085934

```
/home/travis/build/char-lie/stereo-parallel/tests/pgm_io.cpp:57:24: error: no
      viable conversion from 'Image' to 'ULONG' (aka 'unsigned long')
    struct Image image{*pgm_io.get_image()};
                       ^~~~~~~~~~~~~~~~~~~
/home/travis/build/char-lie/stereo-parallel/tests/pgm_io.cpp:57:43: error: 
      missing field 'height' initializer [-Werror,-Wmissing-field-initializers]
    struct Image image{*pgm_io.get_image()};
                                          ^
```

The issue was discussed on bugtracker of GCC
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=36750
as well as on CLang forum
http://clang-developers.42468.n3.nabble.com/Wmissing-field-initializers-td3761260.html

It was fixed in the next versions of compilers,
so I will simply remove them from CI.
Also, this will shorten time of tests running.