Fix uninitialized value usage
I've thought that the error is a false positive
https://travis-ci.org/char-lie/stereo-parallel/jobs/458166248
```
/home/travis/build/char-lie/stereo-parallel/include/pgm_io.cpp:75:27: error: The left operand of '==' is a garbage value [clang-analyzer-core.UndefinedBinaryOperatorResult,-warnings-as-errors]
        if (current_input == '#')
                          ^
```

It appeared that I've used `get` after loop iteration instead of before,
so on the first iteration the value was `\0`
and I've hardcoded the check for it.
Now it works good without that "workaround".