Fix llvm-header-guard error
Build failed
https://travis-ci.org/char-lie/stereo-parallel/jobs/443290526

```
/home/travis/build/char-lie/stereo-parallel/src/image.hpp:24:9: error:
header guard does not follow preferred style
[llvm-header-guard,-warnings-as-errors]
        ^~~~~~~
        _HOME_TRAVIS_BUILD_CHAR_LIE_STEREO_PARALLEL_SRC_IMAGE_HPP
```

Description of failed rule didn't get much information
about proper format.
https://clang.llvm.org/extra/clang-tidy/checks/llvm-header-guard.html

Linter proposed me to place full path
to `image.hpp` file into guard name.
On StackOverflow
https://stackoverflow.com/a/43881045/1305036
I've found a link to tests of clang-tidy
https://github.com/llvm-mirror/clang-tools-extra/blob/c30b89a5fed67aff8eead6412b97af97afdee019/unittests/clang-tidy/LLVMModuleTest.cpp
There I see that files in tests are placed in `include` folder.

I need to rename `src` folder to `include`
and change corresponding reference in main CMakeLists.txt file.
Perfect, this works!